### ISSUE TITLE
BeerJS #1 Discussion

### ISSUE THREAD

**Issue by ElForastero** [beerjs/togliatti#2]
🍺 October 28, Saturday. 5 PM. After [WedDev meetup](http://wdmeetup.ru).

We still think of the place. You can suggest one.

### Registration
Actually, it's not necessary to register, but will be better if we will know how much participants we will have. This will be useful while choosing a place.

Please comment this issue, or just use an emoji. 🍺

**Comment by ElForastero** [comment]
Can't assign @SmirnovW

**Comment by DonRai** [comment]
I suggest [Vedro Gvozdei](https://www.google.ru/search?q=%D1%82%D0%BE%D0%BB%D1%8C%D1%8F%D1%82%D1%82%D0%B8%20%D0%B1%D0%B0%D1%80%D1%8B&oq=njkmznnb+%2Cfhs&aqs=chrome.2.69i57j0l5.3351j0j7&sourceid=chrome&ie=UTF-8&newwindow=1&npsic=0&rflfq=1&rlha=0&rllag=53526391,49312409,2612&tbm=lcl&rldimm=7140106894976976709&ved=0ahUKEwjD_Y_x34jXAhXKHpoKHW54Ao8QvS4ITDAB&rldoc=1&tbs=lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9#rlfi=hd:;si:7140106894976976709;mv:!1m3!1d22089.70151905251!2d49.30684395!3d53.5211897!2m3!1f0!2f0!3f0!3m2!1i589!2i447!4f13.1;tbs:lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9) if we have about 5-8 people

**Comment by DonRai** [comment]
And I think need announce in our VK group about this event, and open registration on beers in github issue. @ElForastero @pbelyaev

**Comment by pbtlt** [comment]
I would suggest FrauGretta as one of the best pubs in TLT

**Comment by ElForastero** [comment]
@pbtlt Is there enough place for around 25 peoples?
