### ISSUE TITLE
BeerJS #2 Registration

### ISSUE THREAD

**Issue by ElForastero** [beerjs/togliatti#6]
June 16, 2018. 17:00?
Where and how?

**Comment by pbelyaev** [comment]
There is a pool on the vk community's wall here (https://vk.com/webdevmeetup?w=wall-133088298_113). @ElForastero, @DonRai,  any thoughts on current pool results?

<img width="630" alt="screen shot 2018-06-11 at 6 22 36 pm" src="https://user-images.githubusercontent.com/6713852/41237437-895d7a5c-6da4-11e8-89a9-04a7e4a21a66.png">

**Comment by ElForastero** [comment]
By the number of votes, we have decided to go to the Beer Hall.
