### ISSUE TITLE
Is this group active?

### ISSUE THREAD

**Issue by Iltimirov** [beerjs/togliatti#7]
Hello there!
Does this community has a telegram or something like it to communicate?
How I can find it?
I would like to meet but don't know how to find you

**Comment by ElForastero** [comment]
Nope :)

**Comment by Iltimirov** [comment]
Maybe create it? I think it would be great. I can create it if you don't mind

**Comment by pbelyaev** [comment]
Hello @Iltimirov.

Please, feel free to create one. Once you do, please share it here. Also, it would be really great to add it to the repo README.

**Comment by Iltimirov** [comment]
done!
[t.me/beerjs_tlt](https://t.me/beerjs_tlt)

feel free to add your friends here, I will add too but it need some time %)
And OFC I will give you and contributors admin rights

**Comment by pbelyaev** [comment]
Let's close this issue and continue the discussion on the telegram chat :) 
Thank you @Iltimirov
